@startuml "Контекстная диаграмма - Система открытия депозитов онлайн"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title "Контекстная диаграмма - Система открытия депозитов онлайн"

Person(client, "Клиент", "Клиент банка, который хочет открыть депозит")
Person(callCenterOperator, "Сотрудник кол-центра", "Обрабатывает заявки с сайта")
Person(backOfficeEmployee, "Сотрудник бэк-офиса", "Обрабатывает заявки и управляет ставками")

System(depositSystem, "Система открытия депозитов онлайн", "Позволяет клиентам подавать заявки и открывать депозиты онлайн")
System_Ext(smsGateway, "SMS-шлюз", "Отправляет SMS-уведомления и коды подтверждения")

Rel(client, depositSystem, "Просматривает депозиты, подает заявки, открывает депозиты")
Rel(callCenterOperator, depositSystem, "Обрабатывает заявки с сайта")
Rel(backOfficeEmployee, depositSystem, "Обрабатывает заявки, управляет ставками")
Rel(depositSystem, smsGateway, "Отправляет запросы на отправку SMS")
Rel(smsGateway, client, "Отправляет SMS-уведомления и коды подтверждения")

@enduml